---
- name: Automate Docker and Borg backup
  hosts: localhost
  tasks:
    - name: Execute pg_dump inside docker container
      command: docker exec lago-db bash -c "pg_dump -U lago lago > /tmp/db_backup.sql"

    - name: Copy backup file from docker container to host
      command: docker cp lago-db:/tmp/db_backup.sql /root/lago_backup/db_backup.sql

- name: Initialize borg repository
  hosts: 194.163.154.164
  tasks:
    - name: Ensure Borg is installed
      package:
        name: borgbackup
        state: present
      become: yes

    - name: Check if borg repository exists
      stat:
        path: /root/lago_backup_repo
      register: repo_stat

    - name: Initialize borg repository with encryption
      command: borg init --encryption=repokey-blake2 /root/lago_backup_repo
      when: not repo_stat.stat.exists
      become: yes

- name: Create borg backup
  hosts: 149.102.140.77
  tasks:
    - name: Ensure Borg is installed
      package:
        name: borgbackup
        state: present
      become: yes

    - name: Check if borg archive exists
      command: borg list root@194.163.154.164:/root/lago_backup_repo
      register: borg_list
      failed_when: false
      changed_when: false

    - name: Create backup using borg
      command: borg create --stats --progress root@194.163.154.164:/root/lago_backup_repo::backup-{{ ansible_date_time.date }} /root/lago_backup
      when: "'backup-{{ ansible_date_time.date }}' not in borg_list.stdout"
      become: yes

- name: Extract borg backup
  hosts: 149.102.140.77
  tasks:
    - name: Ensure Borg is installed
      package:
        name: borgbackup
        state: present
      become: yes

    - name: Create extraction directory
      file:
        path: ~/borg-extract
        state: directory

    - name: Extract data from borg backup
      command: >
        borg extract root@194.163.154.164:/root/lago_backup_repo::backup-{{ ansible_date_time.date }}
      args:
        chdir: ~/borg-extract
      become: yes

