---
- name: Automate Docker and Borg backup
  hosts: 194.163.154.164
  tasks:
    - name: Execute pg_dump inside docker container lago
      command: docker exec lago-db bash -c "pg_dump -U lago lago > /tmp/db_backup.sql"

    - name: Copy backup file from docker container to host
      command: docker cp lago-db:/tmp/db_backup.sql /root/lago_backup/db_backup.sql

    
    - name: Execute pg_dump inside docker container wiki
      command: docker exec requarks-wiki-db-1 bash -c "pg_dump -U wikijs wiki > /tmp/wiki_backup.sql"

    - name: Copy backup file from docker container to host
      command: docker cp requarks-wiki-db-1:/tmp/wiki_backup.sql /root/lago_backup/wiki_backup.sql


    - name: Execute pg_dump inside docker container sonarqube
      command: docker exec sonar-lint-db-1 bash -c "pg_dump -U sonar -d sonar > /tmp/sonarqube_backup.sql"

    - name: Copy backup file from docker container to host
      command: docker cp sonar-lint-db-1:/tmp/sonarqube_backup.sql /root/lago_backup/sonarqube_backup.sql


- name: Initialize borg repository
  hosts: 194.163.154.164
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure Borg is installed
      ansible.builtin.package:
        name: borgbackup
        state: present

    - name: Ensure backup directory exists on the remote host
      file:
        path: /root/lago_backup
        state: directory

    - name: Check if borg repository exists
      stat:
        path: /root/lago_backup_repo
      register: repo_stat

    - name: Initialize borg repository with encryption
      command: borg init --encryption=repokey-blake2 /root/lago_backup_repo
      when: not repo_stat.stat.exists

    - name: Check if borg archive exists
      command: borg list /root/lago_backup_repo
      register: borg_list
      failed_when: false
      changed_when: false

    - name: Reinitialize borg repository if no manifest
      command: borg init --encryption=repokey-blake2 /root/lago_backup_repo
      when: borg_list.rc != 0 and 'Repository has no manifest' in borg_list.stderr

- name: Create borg backup
  hosts: 194.163.154.164
  tasks:
    - name: Ensure Borg is installed
      package:
        name: borgbackup
        state: present
      become: yes

    - name: Check if borg archive exists
      command: borg list /root/lago_backup_repo
      register: borg_list
      failed_when: false
      changed_when: false

    - name: Create backup using borg
      command: borg create --stats --progress /root/lago_backup_repo::backup-{{ ansible_date_time.date }} /root/lago_backup
      when: backup_name not in borg_list.stdout
      vars:
        backup_name: "backup-{{ ansible_date_time.date }}"
        
- name: Extract borg backup
  hosts: 149.102.140.77
  tasks:
    - name: Ensure Borg is installed
      package:
        name: borgbackup
        state: present
      become: yes

    - name: Create extraction directory
      file:
        path: ~/borg-extract
        state: directory

    - name: Extract data from borg backup
      command: >
        borg extract root@194.163.154.164:/root/lago_backup_repo::backup-{{ ansible_date_time.date }}
      args:
        chdir: ~/borg-extract
      become: yes

# ---
# - name: Test SSH connectivity and create a test file
#   hosts: remote
#   tasks:
#     - name: Create a test file on the remote host
#       command: touch /root/test_file.txt

#     - name: Verify the test file was created
#       stat:
#         path: /root/test_file.txt
#       register: test_file

#     - name: Print test file creation status
#       debug:
#         msg: "Test file exists: {{ test_file.stat.exists }}"


