---
- name: Automate Docker and Borg backup
  hosts: localhost
  tasks:
    - name: Ensure the sonarqube_backup directory exists
      file:
        path: /root/sonarqube_backup
        state: directory
        mode: '0755'
        
    - name: Execute pg_dump inside docker container sonarqube
      command: docker exec sonar-lint-db-1 bash -c "pg_dump -U sonar -d sonar > /tmp/sonarqube_backup.sql"

    - name: Copy backup file from docker container to host
      command: docker cp sonar-lint-db-1:/tmp/sonarqube_backup.sql /root/sonarqube_backup/sonarqube_backup.sql

- name: Initialize borg repository
  hosts: 194.163.154.164
  tasks:
    - name: Ensure Borg is installed
      package:
        name: borgbackup
        state: present
      become: yes

    - name: Check if borg repository exists
      stat:
        path: /root/sonarqube_backup_repo
      register: repo_stat

    - name: Initialize borg repository with encryption
      command: borg init --encryption=repokey-blake2 /root/sonarqube_backup_repo
      when: not repo_stat.stat.exists
      become: yes

- name: Create borg backup
  hosts: 194.163.154.164
  tasks:
    - name: Ensure Borg is installed
      package:
        name: borgbackup
        state: present
      become: yes

    - name: Check if borg repository directory exists
      stat:
        path: /root/sonarqube_backup_repo
      register: repo_stat
    
    - name: Initialize borg repository if it doesn't exist
      command: borg init --encryption=none /root/sonarqube_backup_repo
      when: not repo_stat.stat.exists
      become: yes
    
    - name: Check if borg archive exists
      command: borg list /root/sonarqube_backup_repo
      register: borg_list
      failed_when: false
      changed_when: false
    
    - name: Debug borg_list stdout
      debug:
        msg: "{{ borg_list.stdout }}"
    
    - name: Create backup using borg
      command: borg create --stats --progress /root/sonarqube_backup_repo::backup-{{ ansible_date_time.date }} /root/sonarqube_backup
      when: "'backup-' + ansible_date_time.date not in borg_list.stdout"
      environment:
        BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK: "yes"
      become: yes


- name: Extract borg backup
  hosts: 149.102.140.77
  tasks:
    - name: Ensure Borg is installed
      package:
        name: borgbackup
        state: present
      become: yes

    - name: Create extraction directory
      file:
        path: ~/borg-extract
        state: directory

    - name: Extract data from borg backup
      command: >
        borg extract root@194.163.154.164:/root/sonarqube_backup_repo::backup-{{ ansible_date_time.date }}
      args:
        chdir: ~/borg-extract
      become: yes
      
