name: Create Pull Request on Issue Close

on:
  issues:
    types:
      - closed

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "fal7w"
          git config --global user.email "f.alfalahi@fintechsys.net"

      - name: Create Pull Request
        run: |
          gh pr create --title "New Pull Request" --body "This pull request is automatically created when the issue is closed." --base main --head "git-act"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
