name: Create Pull Request on Issue Close

on:
  issues:
    types:
      - closed

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "title": "New Pull Request",
              "body": "This pull request is automatically created when the issue is closed.",
              "head": "selected-branch",
              "base": "main"
            }' \
            "https://api.github.com/repos/${{ github.repository }}/pulls"
            
