name:  Deadline_schedule_v2

on: 
   schedule:
    - cron: '*/2 * * * *'  # Run every 2 minutes
env:
  DEV_DIR: Scripts

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out Scripts repository
      uses: actions/checkout@v4
      with:
        repository: fal7w/Scripts
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEV_DIR }}

    - name: Notify Deadline
      run: python ${{ env.DEV_DIR }}/Deadline_script.py
      shell: sh

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: mail.fintechsys.net
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Today is the deadline!'
        message: "this notify for deadline"
        to: ${{ secrets.USERS_EMAILS }}
        from: github-actions@gmail.com
