name:  Deadline_schedule_v2

on: 
   schedule:
    - cron: '*/2 * * * *'  # Run every 2 minutes

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

      - name: checkout Script content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install dependicese
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyGithub

      - name: execute py script # run main.py
        # env:
        #   SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python deadline_notify.py

      - name: commit files
        run: |
          git config --local user.email "f.alfalahi@fintechsys.net"
          git config --local user.name "fal7w"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
           server_address: mail.fintechsys.net
           server_port: 465
           username: ${{ secrets.EMAIL_USERNAME }}
           password: ${{ secrets.EMAIL_PASSWORD }}
           subject: 'Today is the deadline!'
           message: "this notify for deadline"
           to: ${{ secrets.USERS_EMAILS }}
           from: github-actions@gmail.com
