name: Deadline Notification

on:
  schedule:
    # Run the workflow every day at 9 AM UTC
    - cron: '0 10 * * *'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run script
        id: run-script
        run: |
          # Write your notification logic using JavaScript
          const today = new Date();
          const deadline = new Date(' nov 4, 2023'); // Replace with your deadline date

          let status = '';
          if (today >= deadline) {
            status = 'completed';
            // Add your notification logic here, such as sending an email
          } else {
            status = 'pending';
          }

          const formattedDate = deadline.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
          console.log(`The deadline status is ${status}`);
          console.log(`Deadline: ${formattedDate}`);

          // Set the output for the status and formatted date
          console.log(`::set-output name=status::${status}`)
          console.log(`::set-output name=formatted-date::${formattedDate}`)

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.fintechsys.net
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Deadline Notification
          body: |
            The deadline status is ${{ steps.run-script.outputs.status }}
            Deadline: ${{ steps.run-script.outputs.formatted-date }}
          to: ${{ secrets.USERS_EMAILS }}
