name: discord_notify

on:
  issues:
    types:
      - opened

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: discord
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            Hello! A new issue has been opened in the repository.
            Issue Title: ${{ github.event.issue.title }}
            Issue URL: ${{ github.event.issue.html_url }}
         
