name: hellow word wrkflow 

on:
  push:
     branches:
       - main
  pull_request:
     branches:
       - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world'
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goobbye
        run: echo "goodbye"
        shell: bash
