name: Send email notification

on:
  issues:
    types:
      - opened

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read HTML file
        id: read_html
        run: |
          curl -o message.html -L "https://github.com/fal7w/Scripts/blob/main/messge.html"  # Replace <URL> with the actual URL of the HTML file

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.fintechsys.net
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'New Issue Opened'
          body: ${{ steps.read_html.outputs.stdout }}
          to: ${{ secrets.USERS_EMAILS }}
          from: github-actions@gmail.com
