name: Create Pull Request on Issue Close

on:
  issues:
    types:
      - closed

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets._GITHUB_TOKEN }}
          branch: 'main'
          title: 'New Pull Request - ${{ github.event.issue.title }}'
          body: 'This pull request was automatically created when the issue was closed.'
