name: New Issue Notification

on:
  issues:
    types:
      - opened

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          channel: '#general'
          message: 'A new issue has been opened in the repository: ${{ github.repository }}'
          username: 'GitHub Actions'
          icon_emoji: ':github:'
