name: Send email notification

on:
  issues:
    types:
      - opened

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.fintechsys.net
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'New Issue Opened'
          body: 'A new issue has been opened in the repository: ${{ github.repository }}'
          to: ${{ Variables.USERS_EMAIL }}
          from: github-actions@gmail.com
