name: Project Item State Notification

on:
   project_card:
      types: [moved]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check card state
        uses: actions/github-script@v6
        id: check_card
        with:
          script: |
            const state = github.event.project_card.column_name;
            console.log('Card state:', state);
            return state;

      - name: Send notification
        if: ${{ steps.check_card.outputs.result == 'Done' }}
        run: |
          echo "Sending notification..."
