name: Pull_Request_Email

on:
  pull_request:
    type:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest

 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.fintechsys.net
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'New pull_request Opened'
          body: |
            Hello! A new pull_request has been opened in the repository.
            pull request Title: ${{ github.event.pull_request.title }}
            pull request URL: ${{ github.event.pull_request.html_url }}
          html_body: |
          
              <!DOCTYPE html>
                <html>
                <head>
                    <meta charset="UTF-8">
                    <title>New Issue Notification</title>
                    <style>
                        body {
                            font-family: Arial, sans-serif;
                            background-color: #f2f2f2;
                            margin: 0;
                            padding: 0;
                            display: flex;
                            justify-content: center;
                            align-items: center;
                            height: 100vh;
                        }
                
                        .container {
                            text-align: center;
                            padding: 30px;
                            background-color: #ffffff;
                            border-radius: 10px;
                            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                        }
                
                        h1 {
                            font-size: 36px;
                            font-weight: bold;
                            line-height: 1.3;
                            margin-bottom: 20px;
                        }
                
                        h2 {
                            font-size: 24px;
                            font-weight: normal;
                            margin-bottom: 10px;
                        }
                
                        a {
                            color: #ff6600;
                            text-decoration: none;
                            transition: color 0.3s ease;
                        }
                
                        a:hover {
                            color: #333333;
                        }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <h1>New pull request Opened</h1>
                        <h2>pull request Title: <span id="issueTitle"> ${{ github.event.pull_request.title }} </span></h2>
                        <h2>pull request URL: <a id="issueURL" href=" " target="_blank"> ${{ github.event.pull_request.html_url }} </a></h2>
                    </div>
                </body>
                <script>
                    async function fetchIssueData() {
                        try {
                            const response = await fetch('message.html');
                            const data = await response.text();
                            const parser = new DOMParser();
                            const htmlContent = parser.parseFromString(data, 'text/html');
                            const issueTitle = htmlContent.getElementById('issueTitle').textContent;
                            const issueURL = htmlContent.getElementById('issueURL').textContent;
                
                            document.getElementById('issueTitle').innerText = issueTitle;
                            document.getElementById('issueURL').href = issueURL;
                            document.getElementById('issueURL').innerText = issueURL;
                        } catch (error) {
                            console.error('Error fetching issue data:', error);
                        }
                    }
                
                    document.addEventListener('DOMContentLoaded', function() {
                        fetchIssueData();
                    });
                </script>
                </html>
          
          to: ${{ secrets.USERS_EMAILS }}
          from: github-actions@gmail.com
