name: Pull Request Notification

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord notification
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: 'A new pull request has been opened or updated in the repository: ${{ github.repository }}'
