name: Reusable workflow 

on:
  workflow_call:


jobs:
  rul_job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Script content
        uses: actions/checkout@v2


      - name: write same thing
        run: |
          git clone https://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@github.com/malnozili/remittance_image_builder.git
